allowBuilds:
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
