import { type Dictionary, t } from "intlayer";

const dashboardContent = {
  key: "dashboard",
  content: {
    title: t({ en: "My account", fr: "Mon compte" }),
    loading: t({ en: "Loading...", fr: "Chargement..." }),
    welcome: t({ en: "Welcome back", fr: "Bon retour" }),
    email: t({ en: "Email", fr: "Email" }),
    userID: t({ en: "User ID", fr: "Identifiant" }),
    role: t({ en: "Role", fr: "Rôle" }),
    roleCustomer: t({ en: "Customer", fr: "Client" }),
    roleAdmin: t({ en: "Administrator", fr: "Administrateur" }),
    accountInfo: t({ en: "Account information", fr: "Informations du compte" }),
    protectedTitle: t({ en: "Protected information", fr: "Informations protégées" }),
    protectedHint: t({
      en: "This section displays data only accessible to authenticated users.",
      fr: "Cette section affiche des données accessibles uniquement aux utilisateurs connectés.",
    }),
    lastAccess: t({ en: "Last accessed", fr: "Dernier accès" }),
    logout: t({ en: "Log out", fr: "Se déconnecter" }),
    goToShop: t({ en: "Back to the boutique", fr: "Retour à la boutique" }),
    secretUnavailable: t({ en: "No protected data available.", fr: "Aucune donnée protégée disponible." }),
    dashboard: t({ en: "Dashboard", fr: "Tableau de bord" }),
    navigate: t({ en: "Navigation", fr: "Navigation" }),
    overview: t({ en: "Overview", fr: "Aperçu" }),
    orders: t({ en: "My orders", fr: "Mes commandes" }),
    favorites: t({ en: "Favorites", fr: "Favoris" }),
    settings: t({ en: "Settings", fr: "Paramètres" }),
    memberSince: t({ en: "Member since", fr: "Membre depuis" }),
    statusOnline: t({ en: "Online", fr: "En ligne" }),

    profileHeading: t({ en: "My profile", fr: "Mon profil" }),
    profileSubtitle: t({
      en: "Manage your photo and personal information",
      fr: "Gérez votre photo et vos informations personnelles",
    }),
    changePhoto: t({ en: "Change photo", fr: "Changer la photo" }),
    removePhoto: t({ en: "Remove photo", fr: "Retirer la photo" }),
    photoSaved: t({ en: "Photo updated!", fr: "Photo mise à jour !" }),
    photoError: t({ en: "Failed to update the photo.", fr: "Échec de la mise à jour de la photo." }),
    profileSaved: t({ en: "Profile updated!", fr: "Profil mis à jour !" }),
    profileError: t({ en: "Failed to update the profile.", fr: "Échec de la mise à jour du profil." }),
    firstName: t({ en: "First name", fr: "Prénom" }),
    lastName: t({ en: "Last name", fr: "Nom" }),
    phone: t({ en: "Phone", fr: "Téléphone" }),
    save: t({ en: "Save", fr: "Enregistrer" }),
    saving: t({ en: "Saving...", fr: "Enregistrement..." }),
    avatarAlt: t({ en: "Profile picture", fr: "Photo de profil" }),
    uploading: t({ en: "Uploading...", fr: "Chargement..." }),

    stats: t({ en: "At a glance", fr: "En un coup d'œil" }),
    ordersCount: t({ en: "Orders", fr: "Commandes" }),
    cartCount: t({ en: "Items in cart", fr: "Articles au panier" }),
    totalSpent: t({ en: "Total spent", fr: "Total dépensé" }),
    emptyOrders: t({ en: "You don't have any orders yet.", fr: "Vous n'avez pas encore de commande." }),
    emptyOrdersDesc: t({
      en: "Start exploring the boutique and place your first order.",
      fr: "Commencez à explorer la boutique et passez votre première commande.",
    }),
    emptyFavorites: t({ en: "No favorites yet.", fr: "Aucun favori pour le moment." }),
    emptyFavoritesDesc: t({
      en: "Your favorite products will appear here.",
      fr: "Vos produits favoris apparaîtront ici.",
    }),
    orderNumber: t({ en: "Order", fr: "Commande" }),
    date: t({ en: "Date", fr: "Date" }),
    total: t({ en: "Total", fr: "Total" }),
    status: t({ en: "Status", fr: "Statut" }),
    viewOrder: t({ en: "View", fr: "Voir" }),
  },
} satisfies Dictionary;

export default dashboardContent;