/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressCreate
 */
export interface AddressCreate {
    /**
     * 
     * @type {string}
     * @memberof AddressCreate
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreate
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreate
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreate
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreate
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreate
     */
    country: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddressCreate
     */
    isDefault?: boolean;
}

/**
 * Check if a given object implements the AddressCreate interface.
 */
export function instanceOfAddressCreate(value: object): value is AddressCreate {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('street' in value) || value['street'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function AddressCreateFromJSON(json: any): AddressCreate {
    return AddressCreateFromJSONTyped(json, false);
}

export function AddressCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'street': json['street'],
        'city': json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'postalCode': json['postalCode'],
        'country': json['country'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
    };
}

export function AddressCreateToJSON(json: any): AddressCreate {
    return AddressCreateToJSONTyped(json, false);
}

export function AddressCreateToJSONTyped(value?: AddressCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'street': value['street'],
        'city': value['city'],
        'state': value['state'],
        'postalCode': value['postalCode'],
        'country': value['country'],
        'isDefault': value['isDefault'],
    };
}

