/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressUpdate
 */
export interface AddressUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddressUpdate
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdate
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdate
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdate
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdate
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdate
     */
    country?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddressUpdate
     */
    isDefault?: boolean;
}

/**
 * Check if a given object implements the AddressUpdate interface.
 */
export function instanceOfAddressUpdate(value: object): value is AddressUpdate {
    return true;
}

export function AddressUpdateFromJSON(json: any): AddressUpdate {
    return AddressUpdateFromJSONTyped(json, false);
}

export function AddressUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'street': json['street'] == null ? undefined : json['street'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'country': json['country'] == null ? undefined : json['country'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
    };
}

export function AddressUpdateToJSON(json: any): AddressUpdate {
    return AddressUpdateToJSONTyped(json, false);
}

export function AddressUpdateToJSONTyped(value?: AddressUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'street': value['street'],
        'city': value['city'],
        'state': value['state'],
        'postalCode': value['postalCode'],
        'country': value['country'],
        'isDefault': value['isDefault'],
    };
}

