/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Brand
 */
export interface Brand {
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    website?: string;
    /**
     * 
     * @type {Date}
     * @memberof Brand
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Brand interface.
 */
export function instanceOfBrand(value: object): value is Brand {
    return true;
}

export function BrandFromJSON(json: any): Brand {
    return BrandFromJSONTyped(json, false);
}

export function BrandFromJSONTyped(json: any, ignoreDiscriminator: boolean): Brand {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'website': json['website'] == null ? undefined : json['website'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function BrandToJSON(json: any): Brand {
    return BrandToJSONTyped(json, false);
}

export function BrandToJSONTyped(value?: Brand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'logo': value['logo'],
        'website': value['website'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

