/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemCreate
 */
export interface CartItemCreate {
    /**
     * 
     * @type {number}
     * @memberof CartItemCreate
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemCreate
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemCreate
     */
    quantity: number;
}

/**
 * Check if a given object implements the CartItemCreate interface.
 */
export function instanceOfCartItemCreate(value: object): value is CartItemCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CartItemCreateFromJSON(json: any): CartItemCreate {
    return CartItemCreateFromJSONTyped(json, false);
}

export function CartItemCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'productId': json['productId'],
        'quantity': json['quantity'],
    };
}

export function CartItemCreateToJSON(json: any): CartItemCreate {
    return CartItemCreateToJSONTyped(json, false);
}

export function CartItemCreateToJSONTyped(value?: CartItemCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

