/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemUpdate
 */
export interface CartItemUpdate {
    /**
     * 
     * @type {number}
     * @memberof CartItemUpdate
     */
    quantity: number;
}

/**
 * Check if a given object implements the CartItemUpdate interface.
 */
export function instanceOfCartItemUpdate(value: object): value is CartItemUpdate {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CartItemUpdateFromJSON(json: any): CartItemUpdate {
    return CartItemUpdateFromJSONTyped(json, false);
}

export function CartItemUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
    };
}

export function CartItemUpdateToJSON(json: any): CartItemUpdate {
    return CartItemUpdateToJSONTyped(json, false);
}

export function CartItemUpdateToJSONTyped(value?: CartItemUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
    };
}

