/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface CartItem
 */
export interface CartItem {
    /**
     * 
     * @type {number}
     * @memberof CartItem
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItem
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItem
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItem
     */
    quantity?: number;
    /**
     * 
     * @type {Date}
     * @memberof CartItem
     */
    addedAt?: Date;
    /**
     * 
     * @type {Product}
     * @memberof CartItem
     */
    product?: Product;
}

/**
 * Check if a given object implements the CartItem interface.
 */
export function instanceOfCartItem(value: object): value is CartItem {
    return true;
}

export function CartItemFromJSON(json: any): CartItem {
    return CartItemFromJSONTyped(json, false);
}

export function CartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'addedAt': json['addedAt'] == null ? undefined : (new Date(json['addedAt'])),
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
    };
}

export function CartItemToJSON(json: any): CartItem {
    return CartItemToJSONTyped(json, false);
}

export function CartItemToJSONTyped(value?: CartItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'productId': value['productId'],
        'quantity': value['quantity'],
        'addedAt': value['addedAt'] == null ? value['addedAt'] : value['addedAt'].toISOString(),
        'product': ProductToJSON(value['product']),
    };
}

