/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderStatusUpdate
 */
export interface OrderStatusUpdate {
    /**
     * 
     * @type {string}
     * @memberof OrderStatusUpdate
     */
    status: string;
}

/**
 * Check if a given object implements the OrderStatusUpdate interface.
 */
export function instanceOfOrderStatusUpdate(value: object): value is OrderStatusUpdate {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrderStatusUpdateFromJSON(json: any): OrderStatusUpdate {
    return OrderStatusUpdateFromJSONTyped(json, false);
}

export function OrderStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStatusUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function OrderStatusUpdateToJSON(json: any): OrderStatusUpdate {
    return OrderStatusUpdateToJSONTyped(json, false);
}

export function OrderStatusUpdateToJSONTyped(value?: OrderStatusUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

