/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressCreate } from './AddressCreate';
import {
    AddressCreateFromJSON,
    AddressCreateFromJSONTyped,
    AddressCreateToJSON,
    AddressCreateToJSONTyped,
} from './AddressCreate';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface OrderCreate
 */
export interface OrderCreate {
    /**
     * 
     * @type {number}
     * @memberof OrderCreate
     */
    userId: number;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof OrderCreate
     */
    orderItems: Array<OrderItem>;
    /**
     * 
     * @type {AddressCreate}
     * @memberof OrderCreate
     */
    billingAddress?: AddressCreate;
    /**
     * 
     * @type {AddressCreate}
     * @memberof OrderCreate
     */
    shippingAddress?: AddressCreate;
    /**
     * 
     * @type {string}
     * @memberof OrderCreate
     */
    notes?: string;
}

/**
 * Check if a given object implements the OrderCreate interface.
 */
export function instanceOfOrderCreate(value: object): value is OrderCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('orderItems' in value) || value['orderItems'] === undefined) return false;
    return true;
}

export function OrderCreateFromJSON(json: any): OrderCreate {
    return OrderCreateFromJSONTyped(json, false);
}

export function OrderCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'orderItems': ((json['orderItems'] as Array<any>).map(OrderItemFromJSON)),
        'billingAddress': json['billingAddress'] == null ? undefined : AddressCreateFromJSON(json['billingAddress']),
        'shippingAddress': json['shippingAddress'] == null ? undefined : AddressCreateFromJSON(json['shippingAddress']),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function OrderCreateToJSON(json: any): OrderCreate {
    return OrderCreateToJSONTyped(json, false);
}

export function OrderCreateToJSONTyped(value?: OrderCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'orderItems': ((value['orderItems'] as Array<any>).map(OrderItemToJSON)),
        'billingAddress': AddressCreateToJSON(value['billingAddress']),
        'shippingAddress': AddressCreateToJSON(value['shippingAddress']),
        'notes': value['notes'],
    };
}

