/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    orderNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    taxAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    shippingAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    discountAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    notes?: string | null;
    /**
     * 
     * @type {Address}
     * @memberof Order
     */
    billingAddress?: Address;
    /**
     * 
     * @type {Address}
     * @memberof Order
     */
    shippingAddress?: Address;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    userId?: number;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof Order
     */
    orderItems?: Array<OrderItem>;
    /**
     * 
     * @type {Date}
     * @memberof Order
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Order
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Order interface.
 */
export function instanceOfOrder(value: object): value is Order {
    return true;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orderNumber': json['orderNumber'] == null ? undefined : json['orderNumber'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'taxAmount': json['taxAmount'] == null ? undefined : json['taxAmount'],
        'shippingAmount': json['shippingAmount'] == null ? undefined : json['shippingAmount'],
        'discountAmount': json['discountAmount'] == null ? undefined : json['discountAmount'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'billingAddress': json['billingAddress'] == null ? undefined : AddressFromJSON(json['billingAddress']),
        'shippingAddress': json['shippingAddress'] == null ? undefined : AddressFromJSON(json['shippingAddress']),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'orderItems': json['orderItems'] == null ? undefined : ((json['orderItems'] as Array<any>).map(OrderItemFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function OrderToJSON(json: any): Order {
    return OrderToJSONTyped(json, false);
}

export function OrderToJSONTyped(value?: Order | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orderNumber': value['orderNumber'],
        'status': value['status'],
        'totalAmount': value['totalAmount'],
        'taxAmount': value['taxAmount'],
        'shippingAmount': value['shippingAmount'],
        'discountAmount': value['discountAmount'],
        'notes': value['notes'],
        'billingAddress': AddressToJSON(value['billingAddress']),
        'shippingAddress': AddressToJSON(value['shippingAddress']),
        'userId': value['userId'],
        'orderItems': value['orderItems'] == null ? undefined : ((value['orderItems'] as Array<any>).map(OrderItemToJSON)),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

