/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    orderId?: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    transactionId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    paymentDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'method': json['method'] == null ? undefined : json['method'],
        'status': json['status'] == null ? undefined : json['status'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'paymentDate': json['paymentDate'] == null ? undefined : (new Date(json['paymentDate'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function PaymentToJSON(json: any): Payment {
    return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(value?: Payment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orderId': value['orderId'],
        'amount': value['amount'],
        'method': value['method'],
        'status': value['status'],
        'transactionId': value['transactionId'],
        'paymentDate': value['paymentDate'] == null ? value['paymentDate'] : value['paymentDate'].toISOString(),
        'notes': value['notes'],
    };
}

