/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentCreate
 */
export interface PaymentCreate {
    /**
     * 
     * @type {number}
     * @memberof PaymentCreate
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    transactionId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PaymentCreate
     */
    paymentDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    notes?: string;
}

/**
 * Check if a given object implements the PaymentCreate interface.
 */
export function instanceOfPaymentCreate(value: object): value is PaymentCreate {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function PaymentCreateFromJSON(json: any): PaymentCreate {
    return PaymentCreateFromJSONTyped(json, false);
}

export function PaymentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'method': json['method'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'paymentDate': json['paymentDate'] == null ? undefined : (new Date(json['paymentDate'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function PaymentCreateToJSON(json: any): PaymentCreate {
    return PaymentCreateToJSONTyped(json, false);
}

export function PaymentCreateToJSONTyped(value?: PaymentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'method': value['method'],
        'transactionId': value['transactionId'],
        'paymentDate': value['paymentDate'] == null ? value['paymentDate'] : value['paymentDate'].toISOString(),
        'notes': value['notes'],
    };
}

