/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductCreate
 */
export interface ProductCreate {
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    compareAtPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    costPrice?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    sku: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    stock?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreate
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreate
     */
    isFeatured?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreate
     */
    isOnSale?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    weight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    dimensions?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductCreate
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductCreate
     */
    images?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    skinType?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    ingredients?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    usage?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    benefits?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    categoryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    brandId?: number | null;
}

/**
 * Check if a given object implements the ProductCreate interface.
 */
export function instanceOfProductCreate(value: object): value is ProductCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    return true;
}

export function ProductCreateFromJSON(json: any): ProductCreate {
    return ProductCreateFromJSONTyped(json, false);
}

export function ProductCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'compareAtPrice': json['compareAtPrice'] == null ? undefined : json['compareAtPrice'],
        'costPrice': json['costPrice'] == null ? undefined : json['costPrice'],
        'sku': json['sku'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'isFeatured': json['isFeatured'] == null ? undefined : json['isFeatured'],
        'isOnSale': json['isOnSale'] == null ? undefined : json['isOnSale'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'images': json['images'] == null ? undefined : json['images'],
        'skinType': json['skinType'] == null ? undefined : json['skinType'],
        'ingredients': json['ingredients'] == null ? undefined : json['ingredients'],
        'usage': json['usage'] == null ? undefined : json['usage'],
        'benefits': json['benefits'] == null ? undefined : json['benefits'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
    };
}

export function ProductCreateToJSON(json: any): ProductCreate {
    return ProductCreateToJSONTyped(json, false);
}

export function ProductCreateToJSONTyped(value?: ProductCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'compareAtPrice': value['compareAtPrice'],
        'costPrice': value['costPrice'],
        'sku': value['sku'],
        'stock': value['stock'],
        'isActive': value['isActive'],
        'isFeatured': value['isFeatured'],
        'isOnSale': value['isOnSale'],
        'weight': value['weight'],
        'dimensions': value['dimensions'],
        'tags': value['tags'],
        'images': value['images'],
        'skinType': value['skinType'],
        'ingredients': value['ingredients'],
        'usage': value['usage'],
        'benefits': value['benefits'],
        'categoryId': value['categoryId'],
        'brandId': value['brandId'],
    };
}

