/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ProductPage
 */
export interface ProductPage {
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductPage
     */
    items?: Array<Product>;
    /**
     * 
     * @type {number}
     * @memberof ProductPage
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductPage
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductPage
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductPage
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductPage
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductPage
     */
    hasPreviousPage?: boolean;
}

/**
 * Check if a given object implements the ProductPage interface.
 */
export function instanceOfProductPage(value: object): value is ProductPage {
    return true;
}

export function ProductPageFromJSON(json: any): ProductPage {
    return ProductPageFromJSONTyped(json, false);
}

export function ProductPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ProductFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
    };
}

export function ProductPageToJSON(json: any): ProductPage {
    return ProductPageToJSONTyped(json, false);
}

export function ProductPageToJSONTyped(value?: ProductPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ProductToJSON)),
        'page': value['page'],
        'limit': value['limit'],
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'hasNextPage': value['hasNextPage'],
        'hasPreviousPage': value['hasPreviousPage'],
    };
}

