/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    compareAtPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    costPrice?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    stock?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    isFeatured?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    isOnSale?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    weight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    dimensions?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Product
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Product
     */
    images?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    skinType?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    ingredients?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    usage?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    benefits?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    categoryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    brandId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'compareAtPrice': json['compareAtPrice'] == null ? undefined : json['compareAtPrice'],
        'costPrice': json['costPrice'] == null ? undefined : json['costPrice'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'isFeatured': json['isFeatured'] == null ? undefined : json['isFeatured'],
        'isOnSale': json['isOnSale'] == null ? undefined : json['isOnSale'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'images': json['images'] == null ? undefined : json['images'],
        'skinType': json['skinType'] == null ? undefined : json['skinType'],
        'ingredients': json['ingredients'] == null ? undefined : json['ingredients'],
        'usage': json['usage'] == null ? undefined : json['usage'],
        'benefits': json['benefits'] == null ? undefined : json['benefits'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'compareAtPrice': value['compareAtPrice'],
        'costPrice': value['costPrice'],
        'sku': value['sku'],
        'stock': value['stock'],
        'isActive': value['isActive'],
        'isFeatured': value['isFeatured'],
        'isOnSale': value['isOnSale'],
        'weight': value['weight'],
        'dimensions': value['dimensions'],
        'tags': value['tags'],
        'images': value['images'],
        'skinType': value['skinType'],
        'ingredients': value['ingredients'],
        'usage': value['usage'],
        'benefits': value['benefits'],
        'categoryId': value['categoryId'],
        'brandId': value['brandId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

