/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    comment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Review
     */
    isVerified?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'title': json['title'] == null ? undefined : json['title'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ReviewToJSON(json: any): Review {
    return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(value?: Review | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'productId': value['productId'],
        'rating': value['rating'],
        'title': value['title'],
        'comment': value['comment'],
        'isVerified': value['isVerified'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

