/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewCreate
 */
export interface ReviewCreate {
    /**
     * 
     * @type {number}
     * @memberof ReviewCreate
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewCreate
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewCreate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewCreate
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewCreate
     */
    isVerified?: boolean;
}

/**
 * Check if a given object implements the ReviewCreate interface.
 */
export function instanceOfReviewCreate(value: object): value is ReviewCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function ReviewCreateFromJSON(json: any): ReviewCreate {
    return ReviewCreateFromJSONTyped(json, false);
}

export function ReviewCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'rating': json['rating'],
        'title': json['title'] == null ? undefined : json['title'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
    };
}

export function ReviewCreateToJSON(json: any): ReviewCreate {
    return ReviewCreateToJSONTyped(json, false);
}

export function ReviewCreateToJSONTyped(value?: ReviewCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'rating': value['rating'],
        'title': value['title'],
        'comment': value['comment'],
        'isVerified': value['isVerified'],
    };
}

