/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shipment
 */
export interface Shipment {
    /**
     * 
     * @type {number}
     * @memberof Shipment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Shipment
     */
    orderId?: number;
    /**
     * 
     * @type {string}
     * @memberof Shipment
     */
    trackingNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Shipment
     */
    carrier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Shipment
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof Shipment
     */
    shippedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Shipment
     */
    deliveredAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Shipment
     */
    estimatedDelivery?: Date | null;
}

/**
 * Check if a given object implements the Shipment interface.
 */
export function instanceOfShipment(value: object): value is Shipment {
    return true;
}

export function ShipmentFromJSON(json: any): Shipment {
    return ShipmentFromJSONTyped(json, false);
}

export function ShipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shipment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'trackingNumber': json['trackingNumber'] == null ? undefined : json['trackingNumber'],
        'carrier': json['carrier'] == null ? undefined : json['carrier'],
        'status': json['status'] == null ? undefined : json['status'],
        'shippedAt': json['shippedAt'] == null ? undefined : (new Date(json['shippedAt'])),
        'deliveredAt': json['deliveredAt'] == null ? undefined : (new Date(json['deliveredAt'])),
        'estimatedDelivery': json['estimatedDelivery'] == null ? undefined : (new Date(json['estimatedDelivery'])),
    };
}

export function ShipmentToJSON(json: any): Shipment {
    return ShipmentToJSONTyped(json, false);
}

export function ShipmentToJSONTyped(value?: Shipment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orderId': value['orderId'],
        'trackingNumber': value['trackingNumber'],
        'carrier': value['carrier'],
        'status': value['status'],
        'shippedAt': value['shippedAt'] == null ? value['shippedAt'] : value['shippedAt'].toISOString(),
        'deliveredAt': value['deliveredAt'] == null ? value['deliveredAt'] : value['deliveredAt'].toISOString(),
        'estimatedDelivery': value['estimatedDelivery'] == null ? value['estimatedDelivery'] : value['estimatedDelivery'].toISOString(),
    };
}

