/* tslint:disable */
/* eslint-disable */
/**
 * Mino Skincare API
 * API for the Mino Skincare mixed showcase and e-commerce site.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Address,
  AddressCreate,
  AddressUpdate,
  AuthResponse,
  Brand,
  CartItem,
  CartItemCreate,
  CartItemUpdate,
  Category,
  LoginRequest,
  Order,
  OrderCreate,
  OrderStatusUpdate,
  Payment,
  PaymentCreate,
  Product,
  ProductCreate,
  ProductPage,
  ProductUpdate,
  RegisterRequest,
  Review,
  ReviewCreate,
  Shipment,
  User,
  UserUpdate,
} from '../models/index';
import {
    AddressFromJSON,
    AddressToJSON,
    AddressCreateFromJSON,
    AddressCreateToJSON,
    AddressUpdateFromJSON,
    AddressUpdateToJSON,
    AuthResponseFromJSON,
    AuthResponseToJSON,
    BrandFromJSON,
    BrandToJSON,
    CartItemFromJSON,
    CartItemToJSON,
    CartItemCreateFromJSON,
    CartItemCreateToJSON,
    CartItemUpdateFromJSON,
    CartItemUpdateToJSON,
    CategoryFromJSON,
    CategoryToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    OrderFromJSON,
    OrderToJSON,
    OrderCreateFromJSON,
    OrderCreateToJSON,
    OrderStatusUpdateFromJSON,
    OrderStatusUpdateToJSON,
    PaymentFromJSON,
    PaymentToJSON,
    PaymentCreateFromJSON,
    PaymentCreateToJSON,
    ProductFromJSON,
    ProductToJSON,
    ProductCreateFromJSON,
    ProductCreateToJSON,
    ProductPageFromJSON,
    ProductPageToJSON,
    ProductUpdateFromJSON,
    ProductUpdateToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    ReviewFromJSON,
    ReviewToJSON,
    ReviewCreateFromJSON,
    ReviewCreateToJSON,
    ShipmentFromJSON,
    ShipmentToJSON,
    UserFromJSON,
    UserToJSON,
    UserUpdateFromJSON,
    UserUpdateToJSON,
} from '../models/index';

export interface AuthLoginPostRequest {
    loginRequest: LoginRequest;
}

export interface AuthRegisterPostRequest {
    registerRequest: RegisterRequest;
}

export interface CartItemsCartItemIdDeleteRequest {
    cartItemId: number;
}

export interface CartItemsCartItemIdPatchRequest {
    cartItemId: number;
    cartItemUpdate: CartItemUpdate;
}

export interface CartItemsGetRequest {
    userId: number;
}

export interface CartItemsPostRequest {
    cartItemCreate: CartItemCreate;
}

export interface CategoriesCategoryIdGetRequest {
    categoryId: number;
}

export interface OrdersGetRequest {
    userId?: number;
}

export interface OrdersOrderIdGetRequest {
    orderId: number;
}

export interface OrdersOrderIdPatchRequest {
    orderId: number;
    orderStatusUpdate: OrderStatusUpdate;
}

export interface OrdersOrderIdPaymentsGetRequest {
    orderId: number;
}

export interface OrdersOrderIdPaymentsPostRequest {
    orderId: number;
    paymentCreate: PaymentCreate;
}

export interface OrdersOrderIdShipmentsGetRequest {
    orderId: number;
}

export interface OrdersPostRequest {
    orderCreate: OrderCreate;
}

export interface ProductsGetRequest {
    categoryId?: number;
    brandId?: number;
    search?: string;
    skinType?: string;
    minPrice?: number;
    maxPrice?: number;
    featured?: boolean;
    onSale?: boolean;
    sort?: ProductsGetSortEnum;
    page?: number;
    limit?: number;
}

export interface ProductsPostRequest {
    productCreate: ProductCreate;
}

export interface ProductsProductIdDeleteRequest {
    productId: number;
}

export interface ProductsProductIdGetRequest {
    productId: number;
}

export interface ProductsProductIdPatchRequest {
    productId: number;
    productUpdate: ProductUpdate;
}

export interface ProductsProductIdReviewsGetRequest {
    productId: number;
}

export interface ProductsProductIdReviewsPostRequest {
    productId: number;
    reviewCreate: ReviewCreate;
}

export interface UsersUserIdAddressesAddressIdDeleteRequest {
    userId: number;
    addressId: number;
}

export interface UsersUserIdAddressesAddressIdPatchRequest {
    userId: number;
    addressId: number;
    addressUpdate: AddressUpdate;
}

export interface UsersUserIdAddressesGetRequest {
    userId: number;
}

export interface UsersUserIdAddressesPostRequest {
    userId: number;
    addressCreate: AddressCreate;
}

export interface UsersUserIdGetRequest {
    userId: number;
}

export interface UsersUserIdPatchRequest {
    userId: number;
    userUpdate: UserUpdate;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for authLoginPost without sending the request
     */
    async authLoginPostRequestOpts(requestParameters: AuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        };
    }

    /**
     * Connexion utilisateur
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        const requestOptions = await this.authLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Connexion utilisateur
     */
    async authLoginPost(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authRegisterPost without sending the request
     */
    async authRegisterPostRequestOpts(requestParameters: AuthRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        };
    }

    /**
     * Inscription utilisateur
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.authRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Inscription utilisateur
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for brandsGet without sending the request
     */
    async brandsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/brands`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liste des marques
     */
    async brandsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Brand>>> {
        const requestOptions = await this.brandsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BrandFromJSON));
    }

    /**
     * Liste des marques
     */
    async brandsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Brand>> {
        const response = await this.brandsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cartItemsCartItemIdDelete without sending the request
     */
    async cartItemsCartItemIdDeleteRequestOpts(requestParameters: CartItemsCartItemIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cartItemId'] == null) {
            throw new runtime.RequiredError(
                'cartItemId',
                'Required parameter "cartItemId" was null or undefined when calling cartItemsCartItemIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cart-items/{cartItemId}`;
        urlPath = urlPath.replace(`{${"cartItemId"}}`, encodeURIComponent(String(requestParameters['cartItemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Supprimer un article du panier
     */
    async cartItemsCartItemIdDeleteRaw(requestParameters: CartItemsCartItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cartItemsCartItemIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer un article du panier
     */
    async cartItemsCartItemIdDelete(requestParameters: CartItemsCartItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cartItemsCartItemIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for cartItemsCartItemIdPatch without sending the request
     */
    async cartItemsCartItemIdPatchRequestOpts(requestParameters: CartItemsCartItemIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cartItemId'] == null) {
            throw new runtime.RequiredError(
                'cartItemId',
                'Required parameter "cartItemId" was null or undefined when calling cartItemsCartItemIdPatch().'
            );
        }

        if (requestParameters['cartItemUpdate'] == null) {
            throw new runtime.RequiredError(
                'cartItemUpdate',
                'Required parameter "cartItemUpdate" was null or undefined when calling cartItemsCartItemIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cart-items/{cartItemId}`;
        urlPath = urlPath.replace(`{${"cartItemId"}}`, encodeURIComponent(String(requestParameters['cartItemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CartItemUpdateToJSON(requestParameters['cartItemUpdate']),
        };
    }

    /**
     * Mettre à jour la quantité d\'un panier
     */
    async cartItemsCartItemIdPatchRaw(requestParameters: CartItemsCartItemIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CartItem>> {
        const requestOptions = await this.cartItemsCartItemIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartItemFromJSON(jsonValue));
    }

    /**
     * Mettre à jour la quantité d\'un panier
     */
    async cartItemsCartItemIdPatch(requestParameters: CartItemsCartItemIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CartItem> {
        const response = await this.cartItemsCartItemIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cartItemsGet without sending the request
     */
    async cartItemsGetRequestOpts(requestParameters: CartItemsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling cartItemsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cart-items`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liste des articles du panier
     */
    async cartItemsGetRaw(requestParameters: CartItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CartItem>>> {
        const requestOptions = await this.cartItemsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CartItemFromJSON));
    }

    /**
     * Liste des articles du panier
     */
    async cartItemsGet(requestParameters: CartItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CartItem>> {
        const response = await this.cartItemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cartItemsPost without sending the request
     */
    async cartItemsPostRequestOpts(requestParameters: CartItemsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cartItemCreate'] == null) {
            throw new runtime.RequiredError(
                'cartItemCreate',
                'Required parameter "cartItemCreate" was null or undefined when calling cartItemsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cart-items`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CartItemCreateToJSON(requestParameters['cartItemCreate']),
        };
    }

    /**
     * Ajouter un article au panier
     */
    async cartItemsPostRaw(requestParameters: CartItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CartItem>> {
        const requestOptions = await this.cartItemsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartItemFromJSON(jsonValue));
    }

    /**
     * Ajouter un article au panier
     */
    async cartItemsPost(requestParameters: CartItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CartItem> {
        const response = await this.cartItemsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for categoriesCategoryIdGet without sending the request
     */
    async categoriesCategoryIdGetRequestOpts(requestParameters: CategoriesCategoryIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling categoriesCategoryIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categories/{categoryId}`;
        urlPath = urlPath.replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Détails d\'une catégorie
     */
    async categoriesCategoryIdGetRaw(requestParameters: CategoriesCategoryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Category>> {
        const requestOptions = await this.categoriesCategoryIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryFromJSON(jsonValue));
    }

    /**
     * Détails d\'une catégorie
     */
    async categoriesCategoryIdGet(requestParameters: CategoriesCategoryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Category> {
        const response = await this.categoriesCategoryIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for categoriesGet without sending the request
     */
    async categoriesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categories`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liste des catégories
     */
    async categoriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Category>>> {
        const requestOptions = await this.categoriesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryFromJSON));
    }

    /**
     * Liste des catégories
     */
    async categoriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Category>> {
        const response = await this.categoriesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersGet without sending the request
     */
    async ordersGetRequestOpts(requestParameters: OrdersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liste des commandes
     */
    async ordersGetRaw(requestParameters: OrdersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Order>>> {
        const requestOptions = await this.ordersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderFromJSON));
    }

    /**
     * Liste des commandes
     */
    async ordersGet(requestParameters: OrdersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Order>> {
        const response = await this.ordersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersOrderIdGet without sending the request
     */
    async ordersOrderIdGetRequestOpts(requestParameters: OrdersOrderIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling ordersOrderIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Détails d\'une commande
     */
    async ordersOrderIdGetRaw(requestParameters: OrdersOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.ordersOrderIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Détails d\'une commande
     */
    async ordersOrderIdGet(requestParameters: OrdersOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.ordersOrderIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersOrderIdPatch without sending the request
     */
    async ordersOrderIdPatchRequestOpts(requestParameters: OrdersOrderIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling ordersOrderIdPatch().'
            );
        }

        if (requestParameters['orderStatusUpdate'] == null) {
            throw new runtime.RequiredError(
                'orderStatusUpdate',
                'Required parameter "orderStatusUpdate" was null or undefined when calling ordersOrderIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: OrderStatusUpdateToJSON(requestParameters['orderStatusUpdate']),
        };
    }

    /**
     * Mettre à jour le statut d\'une commande
     */
    async ordersOrderIdPatchRaw(requestParameters: OrdersOrderIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.ordersOrderIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Mettre à jour le statut d\'une commande
     */
    async ordersOrderIdPatch(requestParameters: OrdersOrderIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.ordersOrderIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersOrderIdPaymentsGet without sending the request
     */
    async ordersOrderIdPaymentsGetRequestOpts(requestParameters: OrdersOrderIdPaymentsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling ordersOrderIdPaymentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/orders/{orderId}/payments`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Paiements d\'une commande
     */
    async ordersOrderIdPaymentsGetRaw(requestParameters: OrdersOrderIdPaymentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Payment>>> {
        const requestOptions = await this.ordersOrderIdPaymentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PaymentFromJSON));
    }

    /**
     * Paiements d\'une commande
     */
    async ordersOrderIdPaymentsGet(requestParameters: OrdersOrderIdPaymentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Payment>> {
        const response = await this.ordersOrderIdPaymentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersOrderIdPaymentsPost without sending the request
     */
    async ordersOrderIdPaymentsPostRequestOpts(requestParameters: OrdersOrderIdPaymentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling ordersOrderIdPaymentsPost().'
            );
        }

        if (requestParameters['paymentCreate'] == null) {
            throw new runtime.RequiredError(
                'paymentCreate',
                'Required parameter "paymentCreate" was null or undefined when calling ordersOrderIdPaymentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders/{orderId}/payments`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentCreateToJSON(requestParameters['paymentCreate']),
        };
    }

    /**
     * Ajouter un paiement à une commande
     */
    async ordersOrderIdPaymentsPostRaw(requestParameters: OrdersOrderIdPaymentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.ordersOrderIdPaymentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Ajouter un paiement à une commande
     */
    async ordersOrderIdPaymentsPost(requestParameters: OrdersOrderIdPaymentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.ordersOrderIdPaymentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersOrderIdShipmentsGet without sending the request
     */
    async ordersOrderIdShipmentsGetRequestOpts(requestParameters: OrdersOrderIdShipmentsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling ordersOrderIdShipmentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/orders/{orderId}/shipments`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Livraisons d\'une commande
     */
    async ordersOrderIdShipmentsGetRaw(requestParameters: OrdersOrderIdShipmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Shipment>>> {
        const requestOptions = await this.ordersOrderIdShipmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShipmentFromJSON));
    }

    /**
     * Livraisons d\'une commande
     */
    async ordersOrderIdShipmentsGet(requestParameters: OrdersOrderIdShipmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Shipment>> {
        const response = await this.ordersOrderIdShipmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersPost without sending the request
     */
    async ordersPostRequestOpts(requestParameters: OrdersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderCreate'] == null) {
            throw new runtime.RequiredError(
                'orderCreate',
                'Required parameter "orderCreate" was null or undefined when calling ordersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderCreateToJSON(requestParameters['orderCreate']),
        };
    }

    /**
     * Créer une commande
     */
    async ordersPostRaw(requestParameters: OrdersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.ordersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Créer une commande
     */
    async ordersPost(requestParameters: OrdersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.ordersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productsGet without sending the request
     */
    async productsGetRequestOpts(requestParameters: ProductsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['categoryId'] != null) {
            queryParameters['categoryId'] = requestParameters['categoryId'];
        }

        if (requestParameters['brandId'] != null) {
            queryParameters['brandId'] = requestParameters['brandId'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['skinType'] != null) {
            queryParameters['skinType'] = requestParameters['skinType'];
        }

        if (requestParameters['minPrice'] != null) {
            queryParameters['minPrice'] = requestParameters['minPrice'];
        }

        if (requestParameters['maxPrice'] != null) {
            queryParameters['maxPrice'] = requestParameters['maxPrice'];
        }

        if (requestParameters['featured'] != null) {
            queryParameters['featured'] = requestParameters['featured'];
        }

        if (requestParameters['onSale'] != null) {
            queryParameters['onSale'] = requestParameters['onSale'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Récupère la liste des produits avec filtres et pagination.
     * Liste des produits
     */
    async productsGetRaw(requestParameters: ProductsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductPage>> {
        const requestOptions = await this.productsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductPageFromJSON(jsonValue));
    }

    /**
     * Récupère la liste des produits avec filtres et pagination.
     * Liste des produits
     */
    async productsGet(requestParameters: ProductsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductPage> {
        const response = await this.productsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productsPost without sending the request
     */
    async productsPostRequestOpts(requestParameters: ProductsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productCreate'] == null) {
            throw new runtime.RequiredError(
                'productCreate',
                'Required parameter "productCreate" was null or undefined when calling productsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/products`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductCreateToJSON(requestParameters['productCreate']),
        };
    }

    /**
     * Créer un produit
     */
    async productsPostRaw(requestParameters: ProductsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.productsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Créer un produit
     */
    async productsPost(requestParameters: ProductsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.productsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productsProductIdDelete without sending the request
     */
    async productsProductIdDeleteRequestOpts(requestParameters: ProductsProductIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling productsProductIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Supprimer un produit
     */
    async productsProductIdDeleteRaw(requestParameters: ProductsProductIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.productsProductIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer un produit
     */
    async productsProductIdDelete(requestParameters: ProductsProductIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.productsProductIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for productsProductIdGet without sending the request
     */
    async productsProductIdGetRequestOpts(requestParameters: ProductsProductIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling productsProductIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Détails d\'un produit
     */
    async productsProductIdGetRaw(requestParameters: ProductsProductIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.productsProductIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Détails d\'un produit
     */
    async productsProductIdGet(requestParameters: ProductsProductIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.productsProductIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productsProductIdPatch without sending the request
     */
    async productsProductIdPatchRequestOpts(requestParameters: ProductsProductIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling productsProductIdPatch().'
            );
        }

        if (requestParameters['productUpdate'] == null) {
            throw new runtime.RequiredError(
                'productUpdate',
                'Required parameter "productUpdate" was null or undefined when calling productsProductIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProductUpdateToJSON(requestParameters['productUpdate']),
        };
    }

    /**
     * Mettre à jour un produit
     */
    async productsProductIdPatchRaw(requestParameters: ProductsProductIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.productsProductIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Mettre à jour un produit
     */
    async productsProductIdPatch(requestParameters: ProductsProductIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.productsProductIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productsProductIdReviewsGet without sending the request
     */
    async productsProductIdReviewsGetRequestOpts(requestParameters: ProductsProductIdReviewsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling productsProductIdReviewsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/products/{productId}/reviews`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Avis d\'un produit
     */
    async productsProductIdReviewsGetRaw(requestParameters: ProductsProductIdReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Review>>> {
        const requestOptions = await this.productsProductIdReviewsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReviewFromJSON));
    }

    /**
     * Avis d\'un produit
     */
    async productsProductIdReviewsGet(requestParameters: ProductsProductIdReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Review>> {
        const response = await this.productsProductIdReviewsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productsProductIdReviewsPost without sending the request
     */
    async productsProductIdReviewsPostRequestOpts(requestParameters: ProductsProductIdReviewsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling productsProductIdReviewsPost().'
            );
        }

        if (requestParameters['reviewCreate'] == null) {
            throw new runtime.RequiredError(
                'reviewCreate',
                'Required parameter "reviewCreate" was null or undefined when calling productsProductIdReviewsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/products/{productId}/reviews`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewCreateToJSON(requestParameters['reviewCreate']),
        };
    }

    /**
     * Ajouter un avis produit
     */
    async productsProductIdReviewsPostRaw(requestParameters: ProductsProductIdReviewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        const requestOptions = await this.productsProductIdReviewsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * Ajouter un avis produit
     */
    async productsProductIdReviewsPost(requestParameters: ProductsProductIdReviewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.productsProductIdReviewsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersGet without sending the request
     */
    async usersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liste des utilisateurs
     */
    async usersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<User>>> {
        const requestOptions = await this.usersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFromJSON));
    }

    /**
     * Liste des utilisateurs
     */
    async usersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>> {
        const response = await this.usersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersUserIdAddressesAddressIdDelete without sending the request
     */
    async usersUserIdAddressesAddressIdDeleteRequestOpts(requestParameters: UsersUserIdAddressesAddressIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdAddressesAddressIdDelete().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling usersUserIdAddressesAddressIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/addresses/{addressId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"addressId"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Supprimer une adresse
     */
    async usersUserIdAddressesAddressIdDeleteRaw(requestParameters: UsersUserIdAddressesAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.usersUserIdAddressesAddressIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer une adresse
     */
    async usersUserIdAddressesAddressIdDelete(requestParameters: UsersUserIdAddressesAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersUserIdAddressesAddressIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for usersUserIdAddressesAddressIdPatch without sending the request
     */
    async usersUserIdAddressesAddressIdPatchRequestOpts(requestParameters: UsersUserIdAddressesAddressIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdAddressesAddressIdPatch().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling usersUserIdAddressesAddressIdPatch().'
            );
        }

        if (requestParameters['addressUpdate'] == null) {
            throw new runtime.RequiredError(
                'addressUpdate',
                'Required parameter "addressUpdate" was null or undefined when calling usersUserIdAddressesAddressIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}/addresses/{addressId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"addressId"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AddressUpdateToJSON(requestParameters['addressUpdate']),
        };
    }

    /**
     * Mettre à jour une adresse
     */
    async usersUserIdAddressesAddressIdPatchRaw(requestParameters: UsersUserIdAddressesAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Address>> {
        const requestOptions = await this.usersUserIdAddressesAddressIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddressFromJSON(jsonValue));
    }

    /**
     * Mettre à jour une adresse
     */
    async usersUserIdAddressesAddressIdPatch(requestParameters: UsersUserIdAddressesAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Address> {
        const response = await this.usersUserIdAddressesAddressIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersUserIdAddressesGet without sending the request
     */
    async usersUserIdAddressesGetRequestOpts(requestParameters: UsersUserIdAddressesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdAddressesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/addresses`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liste des adresses d\'un utilisateur
     */
    async usersUserIdAddressesGetRaw(requestParameters: UsersUserIdAddressesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Address>>> {
        const requestOptions = await this.usersUserIdAddressesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AddressFromJSON));
    }

    /**
     * Liste des adresses d\'un utilisateur
     */
    async usersUserIdAddressesGet(requestParameters: UsersUserIdAddressesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Address>> {
        const response = await this.usersUserIdAddressesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersUserIdAddressesPost without sending the request
     */
    async usersUserIdAddressesPostRequestOpts(requestParameters: UsersUserIdAddressesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdAddressesPost().'
            );
        }

        if (requestParameters['addressCreate'] == null) {
            throw new runtime.RequiredError(
                'addressCreate',
                'Required parameter "addressCreate" was null or undefined when calling usersUserIdAddressesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}/addresses`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddressCreateToJSON(requestParameters['addressCreate']),
        };
    }

    /**
     * Ajouter une adresse
     */
    async usersUserIdAddressesPostRaw(requestParameters: UsersUserIdAddressesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Address>> {
        const requestOptions = await this.usersUserIdAddressesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddressFromJSON(jsonValue));
    }

    /**
     * Ajouter une adresse
     */
    async usersUserIdAddressesPost(requestParameters: UsersUserIdAddressesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Address> {
        const response = await this.usersUserIdAddressesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersUserIdGet without sending the request
     */
    async usersUserIdGetRequestOpts(requestParameters: UsersUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Détails d\'un utilisateur
     */
    async usersUserIdGetRaw(requestParameters: UsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.usersUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Détails d\'un utilisateur
     */
    async usersUserIdGet(requestParameters: UsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.usersUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersUserIdPatch without sending the request
     */
    async usersUserIdPatchRequestOpts(requestParameters: UsersUserIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdPatch().'
            );
        }

        if (requestParameters['userUpdate'] == null) {
            throw new runtime.RequiredError(
                'userUpdate',
                'Required parameter "userUpdate" was null or undefined when calling usersUserIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateToJSON(requestParameters['userUpdate']),
        };
    }

    /**
     * Mettre à jour un utilisateur
     */
    async usersUserIdPatchRaw(requestParameters: UsersUserIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.usersUserIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Mettre à jour un utilisateur
     */
    async usersUserIdPatch(requestParameters: UsersUserIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.usersUserIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ProductsGetSortEnum = {
    PriceAsc: 'price_asc',
    PriceDesc: 'price_desc',
    Newest: 'newest',
    Popularity: 'popularity'
} as const;
export type ProductsGetSortEnum = typeof ProductsGetSortEnum[keyof typeof ProductsGetSortEnum];
