import { type Dictionary, t } from "intlayer";
import type { Metadata } from "next";

const metadataContent = {
  key: "page-metadata",
  content: {
    title: t({
      en: "Create Next App",
      fr: "Créer une application Next.js",
    }),
    description: t({
      en: "Generated by create next app",
      fr: "Généré par create next app",
    }),
  },
} satisfies Dictionary<Metadata>;

export default metadataContent;
